import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import mapboxgl from 'mapbox-gl';
import { ChakraProvider } from '@chakra-ui/react';
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import '@mantine/core/styles.css';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

mapboxgl.accessToken =
  'pk.eyJ1Ijoiam9qaXRvb24iLCJhIjoiY2xob25yZzdhMGtrMjNlcGVuaTNxNnp0dSJ9.Mp_4_OEGVS7A_bdfuBDtdA';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <MantineProvider>
          <ChakraProvider>{children}</ChakraProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
